/*
  File autogenerated by gengetopt version 2.12.2
  generated with the following command:
  /afs/pdc.kth.se/home/h/hakanv/Private/nfsvol/oldNFS/gengetopt/bin/gengetopt --file-name=cmdline_hmmtrain 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline_hmmtrain.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->hmminfile_given = 0 ;
  args_info->seqnamefile_given = 0 ;
  args_info->seqformat_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->freqfile_given = 0 ;
  args_info->smxfile_given = 0 ;
  args_info->replfile_given = 0 ;
  args_info->alg_given = 0 ;
  args_info->negseqnamefile_given = 0 ;
  args_info->optalpha_given = 0 ;
  args_info->msascoring_given = 0 ;
  args_info->usecolumns_given = 0 ;
  args_info->nolabels_given = 0 ;
  args_info->noprior_given = 0 ;
  args_info->tpcounts_given = 0 ;
  args_info->epcounts_given = 0 ;
  args_info->transonly_given = 0 ;
  args_info->emissonly_given = 0 ;
  args_info->verbose_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->hmminfile_arg = NULL;
  args_info->seqnamefile_arg = NULL;
  args_info->seqformat_arg = NULL;
  args_info->outfile_arg = NULL;
  args_info->freqfile_arg = NULL;
  args_info->smxfile_arg = NULL;
  args_info->replfile_arg = NULL;
  args_info->alg_arg = NULL;
  args_info->negseqnamefile_arg = NULL;
  args_info->optalpha_arg = NULL;
  args_info->msascoring_arg = NULL;
  args_info->usecolumns_arg = NULL;
  args_info->nolabels_flag = 0;
  args_info->noprior_flag = 0;
  args_info->tpcounts_flag = 0;
  args_info->epcounts_flag = 0;
  args_info->transonly_flag = 0;
  args_info->emissonly_flag = 0;
  args_info->verbose_flag = 0;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Purpose:\n"
"  train a hidden markov model\n"
  "\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("\n");
  printf("%s\n","  -h, --help                    Print help and exit");
  printf("%s\n","  -V, --version                 Print version and exit");
  printf("%s\n","  -i, --hmminfile=filename      modelfile (in .hmg format)");
  printf("%s\n","  -s, --seqnamefile=filename    sequence namefile (for sequences in fasta, \n                                  smod, msamod or prfmod format)");
  printf("%s\n","  -f, --seqformat=STRING        format of input sequences (fa=fasta, s=smod, \n                                  msa=msamod, prf=prfmod)");
  printf("%s\n","  -o, --outfile=filename        model outfile");
  printf("%s\n","  -q, --freqfile=filename       background frequency file");
  printf("%s\n","  -x, --smxfile=filename        substitution matrix file");
  printf("%s\n","  -r, --replfile=filename       replacement letter file");
  printf("%s\n","  -a, --alg=STRING              training algorithm (cml=conditional maximum \n                                  likelihood, bw=baum-welch (default), \n                                  disc=discriminative training)");
  printf("%s\n","  -n, --negseqnamefile=filename sequence namefile for negative training \n                                  sequences (for sequences in fasta, smod, \n                                  msamod\n                                  or prfmod format)");
  printf("%s\n","  -z, --optalpha=STRING         alphabet to optimize (parameters for \n                                  transitions and all other alphabets will not \n                                  be changed");
  printf("%s\n","  -M, --msascoring=STRING       scoring method for alignment and profile data \n                                  options = DP/DPPI/GM/GMR/DPPI/PI/PIS \n                                  default=GM");
  printf("%s\n","  -c, --usecolumns=STRING       specify which columns to use for alignment \n                                  input data, options = all/nr, where all means \n                                  use all columns\n                                  and nr specifies a sequence in the alignment \n                                  and the columns where this sequence have \n                                  non-gap symbls are used\n                                  default = all");
  printf("%s\n","      --nolabels                do not use labels even though the input \n                                  sequences are labeled  (default=off)");
  printf("%s\n","      --noprior                 do not use priors when training even though the \n                                  the model file has prior files specified  \n                                  (default=off)");
  printf("%s\n","      --tpcounts                use pseudocounts for transition parameter \n                                  updates  (default=off)");
  printf("%s\n","      --epcounts                use pseudocounts for emission parameter updates \n                                   (default=off)");
  printf("%s\n","      --transonly               only update transition parameters  \n                                  (default=off)");
  printf("%s\n","      --emissonly               only update emission parameters  (default=off)");
  printf("%s\n","  -v, --verbose                 print some information about what is going on  \n                                  (default=off)");
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->hmminfile_arg)
    {
      free (args_info->hmminfile_arg); /* free previous argument */
      args_info->hmminfile_arg = 0;
    }
  if (args_info->seqnamefile_arg)
    {
      free (args_info->seqnamefile_arg); /* free previous argument */
      args_info->seqnamefile_arg = 0;
    }
  if (args_info->seqformat_arg)
    {
      free (args_info->seqformat_arg); /* free previous argument */
      args_info->seqformat_arg = 0;
    }
  if (args_info->outfile_arg)
    {
      free (args_info->outfile_arg); /* free previous argument */
      args_info->outfile_arg = 0;
    }
  if (args_info->freqfile_arg)
    {
      free (args_info->freqfile_arg); /* free previous argument */
      args_info->freqfile_arg = 0;
    }
  if (args_info->smxfile_arg)
    {
      free (args_info->smxfile_arg); /* free previous argument */
      args_info->smxfile_arg = 0;
    }
  if (args_info->replfile_arg)
    {
      free (args_info->replfile_arg); /* free previous argument */
      args_info->replfile_arg = 0;
    }
  if (args_info->alg_arg)
    {
      free (args_info->alg_arg); /* free previous argument */
      args_info->alg_arg = 0;
    }
  if (args_info->negseqnamefile_arg)
    {
      free (args_info->negseqnamefile_arg); /* free previous argument */
      args_info->negseqnamefile_arg = 0;
    }
  if (args_info->optalpha_arg)
    {
      free (args_info->optalpha_arg); /* free previous argument */
      args_info->optalpha_arg = 0;
    }
  if (args_info->msascoring_arg)
    {
      free (args_info->msascoring_arg); /* free previous argument */
      args_info->msascoring_arg = 0;
    }
  if (args_info->usecolumns_arg)
    {
      free (args_info->usecolumns_arg); /* free previous argument */
      args_info->usecolumns_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "hmminfile",	1, NULL, 'i' },
        { "seqnamefile",	1, NULL, 's' },
        { "seqformat",	1, NULL, 'f' },
        { "outfile",	1, NULL, 'o' },
        { "freqfile",	1, NULL, 'q' },
        { "smxfile",	1, NULL, 'x' },
        { "replfile",	1, NULL, 'r' },
        { "alg",	1, NULL, 'a' },
        { "negseqnamefile",	1, NULL, 'n' },
        { "optalpha",	1, NULL, 'z' },
        { "msascoring",	1, NULL, 'M' },
        { "usecolumns",	1, NULL, 'c' },
        { "nolabels",	0, NULL, 0 },
        { "noprior",	0, NULL, 0 },
        { "tpcounts",	0, NULL, 0 },
        { "epcounts",	0, NULL, 0 },
        { "transonly",	0, NULL, 0 },
        { "emissonly",	0, NULL, 0 },
        { "verbose",	0, NULL, 'v' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:s:f:o:q:x:r:a:n:z:M:c:v", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'i':	/* modelfile (in .hmg format).  */
          if (local_args_info.hmminfile_given)
            {
              fprintf (stderr, "%s: `--hmminfile' (`-i') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->hmminfile_given && ! override)
            continue;
          local_args_info.hmminfile_given = 1;
          args_info->hmminfile_given = 1;
          if (args_info->hmminfile_arg)
            free (args_info->hmminfile_arg); /* free previous string */
          args_info->hmminfile_arg = gengetopt_strdup (optarg);
          break;

        case 's':	/* sequence namefile (for sequences in fasta, smod, msamod or prfmod format).  */
          if (local_args_info.seqnamefile_given)
            {
              fprintf (stderr, "%s: `--seqnamefile' (`-s') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->seqnamefile_given && ! override)
            continue;
          local_args_info.seqnamefile_given = 1;
          args_info->seqnamefile_given = 1;
          if (args_info->seqnamefile_arg)
            free (args_info->seqnamefile_arg); /* free previous string */
          args_info->seqnamefile_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* format of input sequences (fa=fasta, s=smod, msa=msamod, prf=prfmod).  */
          if (local_args_info.seqformat_given)
            {
              fprintf (stderr, "%s: `--seqformat' (`-f') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->seqformat_given && ! override)
            continue;
          local_args_info.seqformat_given = 1;
          args_info->seqformat_given = 1;
          if (args_info->seqformat_arg)
            free (args_info->seqformat_arg); /* free previous string */
          args_info->seqformat_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* model outfile.  */
          if (local_args_info.outfile_given)
            {
              fprintf (stderr, "%s: `--outfile' (`-o') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->outfile_given && ! override)
            continue;
          local_args_info.outfile_given = 1;
          args_info->outfile_given = 1;
          if (args_info->outfile_arg)
            free (args_info->outfile_arg); /* free previous string */
          args_info->outfile_arg = gengetopt_strdup (optarg);
          break;

        case 'q':	/* background frequency file.  */
          if (local_args_info.freqfile_given)
            {
              fprintf (stderr, "%s: `--freqfile' (`-q') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->freqfile_given && ! override)
            continue;
          local_args_info.freqfile_given = 1;
          args_info->freqfile_given = 1;
          if (args_info->freqfile_arg)
            free (args_info->freqfile_arg); /* free previous string */
          args_info->freqfile_arg = gengetopt_strdup (optarg);
          break;

        case 'x':	/* substitution matrix file.  */
          if (local_args_info.smxfile_given)
            {
              fprintf (stderr, "%s: `--smxfile' (`-x') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->smxfile_given && ! override)
            continue;
          local_args_info.smxfile_given = 1;
          args_info->smxfile_given = 1;
          if (args_info->smxfile_arg)
            free (args_info->smxfile_arg); /* free previous string */
          args_info->smxfile_arg = gengetopt_strdup (optarg);
          break;

        case 'r':	/* replacement letter file.  */
          if (local_args_info.replfile_given)
            {
              fprintf (stderr, "%s: `--replfile' (`-r') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->replfile_given && ! override)
            continue;
          local_args_info.replfile_given = 1;
          args_info->replfile_given = 1;
          if (args_info->replfile_arg)
            free (args_info->replfile_arg); /* free previous string */
          args_info->replfile_arg = gengetopt_strdup (optarg);
          break;

        case 'a':	/* training algorithm (cml=conditional maximum likelihood, bw=baum-welch (default), disc=discriminative training).  */
          if (local_args_info.alg_given)
            {
              fprintf (stderr, "%s: `--alg' (`-a') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->alg_given && ! override)
            continue;
          local_args_info.alg_given = 1;
          args_info->alg_given = 1;
          if (args_info->alg_arg)
            free (args_info->alg_arg); /* free previous string */
          args_info->alg_arg = gengetopt_strdup (optarg);
          break;

        case 'n':	/* sequence namefile for negative training sequences (for sequences in fasta, smod, msamod
        or prfmod format).  */
          if (local_args_info.negseqnamefile_given)
            {
              fprintf (stderr, "%s: `--negseqnamefile' (`-n') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->negseqnamefile_given && ! override)
            continue;
          local_args_info.negseqnamefile_given = 1;
          args_info->negseqnamefile_given = 1;
          if (args_info->negseqnamefile_arg)
            free (args_info->negseqnamefile_arg); /* free previous string */
          args_info->negseqnamefile_arg = gengetopt_strdup (optarg);
          break;

        case 'z':	/* alphabet to optimize (parameters for transitions and all other alphabets will not be changed.  */
          if (local_args_info.optalpha_given)
            {
              fprintf (stderr, "%s: `--optalpha' (`-z') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->optalpha_given && ! override)
            continue;
          local_args_info.optalpha_given = 1;
          args_info->optalpha_given = 1;
          if (args_info->optalpha_arg)
            free (args_info->optalpha_arg); /* free previous string */
          args_info->optalpha_arg = gengetopt_strdup (optarg);
          break;

        case 'M':	/* scoring method for alignment and profile data options = DP/DPPI/GM/GMR/DPPI/PI/PIS default=GM.  */
          if (local_args_info.msascoring_given)
            {
              fprintf (stderr, "%s: `--msascoring' (`-M') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->msascoring_given && ! override)
            continue;
          local_args_info.msascoring_given = 1;
          args_info->msascoring_given = 1;
          if (args_info->msascoring_arg)
            free (args_info->msascoring_arg); /* free previous string */
          args_info->msascoring_arg = gengetopt_strdup (optarg);
          break;

        case 'c':	/* specify which columns to use for alignment input data, options = all/nr, where all means use all columns
        and nr specifies a sequence in the alignment and the columns where this sequence have non-gap symbls are used
        default = all.  */
          if (local_args_info.usecolumns_given)
            {
              fprintf (stderr, "%s: `--usecolumns' (`-c') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->usecolumns_given && ! override)
            continue;
          local_args_info.usecolumns_given = 1;
          args_info->usecolumns_given = 1;
          if (args_info->usecolumns_arg)
            free (args_info->usecolumns_arg); /* free previous string */
          args_info->usecolumns_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* print some information about what is going on.  */
          if (local_args_info.verbose_given)
            {
              fprintf (stderr, "%s: `--verbose' (`-v') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbose_given && ! override)
            continue;
          local_args_info.verbose_given = 1;
          args_info->verbose_given = 1;
          args_info->verbose_flag = !(args_info->verbose_flag);
          break;


        case 0:	/* Long option with no short option */
          /* do not use labels even though the input sequences are labeled.  */
          if (strcmp (long_options[option_index].name, "nolabels") == 0)
          {
            if (local_args_info.nolabels_given)
              {
                fprintf (stderr, "%s: `--nolabels' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nolabels_given && ! override)
              continue;
            local_args_info.nolabels_given = 1;
            args_info->nolabels_given = 1;
            args_info->nolabels_flag = !(args_info->nolabels_flag);
          }
          
          /* do not use priors when training even though the the model file has prior files specified.  */
          else if (strcmp (long_options[option_index].name, "noprior") == 0)
          {
            if (local_args_info.noprior_given)
              {
                fprintf (stderr, "%s: `--noprior' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->noprior_given && ! override)
              continue;
            local_args_info.noprior_given = 1;
            args_info->noprior_given = 1;
            args_info->noprior_flag = !(args_info->noprior_flag);
          }
          
          /* use pseudocounts for transition parameter updates.  */
          else if (strcmp (long_options[option_index].name, "tpcounts") == 0)
          {
            if (local_args_info.tpcounts_given)
              {
                fprintf (stderr, "%s: `--tpcounts' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->tpcounts_given && ! override)
              continue;
            local_args_info.tpcounts_given = 1;
            args_info->tpcounts_given = 1;
            args_info->tpcounts_flag = !(args_info->tpcounts_flag);
          }
          
          /* use pseudocounts for emission parameter updates.  */
          else if (strcmp (long_options[option_index].name, "epcounts") == 0)
          {
            if (local_args_info.epcounts_given)
              {
                fprintf (stderr, "%s: `--epcounts' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->epcounts_given && ! override)
              continue;
            local_args_info.epcounts_given = 1;
            args_info->epcounts_given = 1;
            args_info->epcounts_flag = !(args_info->epcounts_flag);
          }
          
          /* only update transition parameters.  */
          else if (strcmp (long_options[option_index].name, "transonly") == 0)
          {
            if (local_args_info.transonly_given)
              {
                fprintf (stderr, "%s: `--transonly' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->transonly_given && ! override)
              continue;
            local_args_info.transonly_given = 1;
            args_info->transonly_given = 1;
            args_info->transonly_flag = !(args_info->transonly_flag);
          }
          
          /* only update emission parameters.  */
          else if (strcmp (long_options[option_index].name, "emissonly") == 0)
          {
            if (local_args_info.emissonly_given)
              {
                fprintf (stderr, "%s: `--emissonly' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->emissonly_given && ! override)
              continue;
            local_args_info.emissonly_given = 1;
            args_info->emissonly_given = 1;
            args_info->emissonly_flag = !(args_info->emissonly_flag);
          }
          

          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      if (! args_info->hmminfile_given)
        {
          fprintf (stderr, "%s: '--hmminfile' ('-i') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
      if (! args_info->seqnamefile_given)
        {
          fprintf (stderr, "%s: '--seqnamefile' ('-s') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
      if (! args_info->seqformat_given)
        {
          fprintf (stderr, "%s: '--seqformat' ('-f') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
      if (! args_info->outfile_given)
        {
          fprintf (stderr, "%s: '--outfile' ('-o') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
    }

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  return (EXIT_FAILURE);
}
