/* cmdline_modseqalign.h */

/* File autogenerated by gengetopt version 2.12.2  */

#ifndef CMDLINE_MODSEQALIGN_H
#define CMDLINE_MODSEQALIGN_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "modseqalign"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * hmmfile_arg;	/* model namefile for models in hmg format.  */
  char * target_arg;	/* sequence namefile (for sequences in fasta, smod, msamod or prfmod format).  */
  char * template_arg;	/* sequence namefile (for sequences in fasta, smod, msamod or prfmod format).  */
  char * seqformat_arg;	/* format of input sequences (fa=fasta, s=smod, msa=msamod, prf=prfmod).  */
  char * outfile_arg;	/* model outfile.  */
  char * freqfile_arg;	/* background frequency file.  */
  char * smxfile_arg;	/* substitution matrix file.  */
  char * replfile_arg;	/* replacement letter file.  */
  char * priorfile_arg;	/* sequence prior file (for msa input files).  */
  char * msascoring_arg;	/* scoring method for alignment and profile data options = DP/DPPI/GM/GMR/DPPI/PI/PIS default=GM.  */
  char * usecolumns_arg;	/* specify which columns to use for alignment input data, options = all/nr, where all means use all columns
and nr specifies a sequence in the alignment and the columns where this sequence have non-gap symbls are used
default = all.  */
  int nolabels_flag;	/* do not use labels even though the input sequences are labeled (default=off).  */
  int verbose_flag;	/* print some information about what is going on (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int hmmfile_given ;	/* Whether hmmfile was given.  */
  int target_given ;	/* Whether target was given.  */
  int template_given ;	/* Whether template was given.  */
  int seqformat_given ;	/* Whether seqformat was given.  */
  int outfile_given ;	/* Whether outfile was given.  */
  int freqfile_given ;	/* Whether freqfile was given.  */
  int smxfile_given ;	/* Whether smxfile was given.  */
  int replfile_given ;	/* Whether replfile was given.  */
  int priorfile_given ;	/* Whether priorfile was given.  */
  int msascoring_given ;	/* Whether msascoring was given.  */
  int usecolumns_given ;	/* Whether usecolumns was given.  */
  int nolabels_given ;	/* Whether nolabels was given.  */
  int verbose_given ;	/* Whether verbose was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_MODSEQALIGN_H */
